# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-28 07:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query_db', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bookinfo',
            table='tb_books',
        ),
    ]
